// Generated by CoffeeScript 2.5.1
module.exports = function() {
  return function(request, response, next) {
    var param, paramName, ref, ref1;
    if (request != null ? (ref = request.swagger) != null ? ref.params : void 0 : void 0) {
      ref1 = request.swagger.params;
      for (paramName in ref1) {
        param = ref1[paramName];
        if (request.params[paramName] != null) {
          param.value = request.params[paramName];
        }
      }
    }
    return next();
  };
};
