// Generated by CoffeeScript 2.5.1
var RedirectResponse, Response, responder;

responder = require('./responder');

exports.Response = Response = class Response {
  constructor(body = null, headers = {}, statusCode1 = 200) {
    this.body = body;
    this.headers = headers;
    this.statusCode = statusCode1;
  }

};

exports.RedirectResponse = RedirectResponse = class RedirectResponse extends Response {
  constructor(uri, statusCode = 301) {
    super(null, {
      Location: uri
    }, statusCode);
    this.uri = uri;
    this.statusCode = statusCode;
  }

};
